services:
  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pj
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # optional seeding

volumes:
  pgdata: